---
# ansible-lint: skip_list=var-naming
device_edge_preflight_admin_user: \"{{ healthcheck_common_admin_user | default('admin') }}\"
device_edge_preflight_container_rootless: false
device_edge_preflight_sudo_group: \"{{ healthcheck_common_sudo_group | default('wheel') }}\"
device_edge_product_repos: []
device_edge_product_prereq_packages: []
device_edge_product_required_secrets: []
device_edge_product_required_mounts: []
device_edge_installer_config_path: /etc/device_edge-installer.conf
device_edge_product_ports: []
device_edge_install_deps: false
device_edge_apply_changes: false
device_edge_validate_platform_certs: false
device_edge_show_help: false
device_edge_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
device_edge_container_runtime: podman
device_edge_container_registry: registry.redhat.io
