---
# ansible-lint: skip_list=var-naming
openshift_ai_preflight_admin_user: admin
openshift_ai_preflight_container_rootless: false
openshift_ai_preflight_sudo_group: wheel
openshift_ai_product_repos: []
openshift_ai_product_prereq_packages: []
openshift_ai_product_required_secrets: []
openshift_ai_product_required_mounts: []
openshift_ai_installer_config_path: /etc/openshift_ai-installer.conf
openshift_ai_product_ports: []
openshift_ai_install_deps: false
openshift_ai_apply_changes: false
openshift_ai_validate_platform_certs: false
openshift_ai_show_help: false
openshift_ai_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
openshift_ai_container_runtime: podman
openshift_ai_container_registry: registry.redhat.io
