---
data_grid_postinstall_admin_user: admin
data_grid_postinstall_sudo_group: wheel
data_grid_product_repos: []
data_grid_product_prereq_packages: []
data_grid_product_required_secrets: []
data_grid_product_required_mounts: []
data_grid_installer_config_path: /etc/data_grid-installer.conf
data_grid_product_ports: []
data_grid_install_deps: false
data_grid_apply_changes: false
data_grid_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
data_grid_container_runtime: podman
data_grid_container_registry: registry.redhat.io
