---
# ansible-lint: skip_list=var-naming
ai_enterprise_preflight_admin_user: admin
ai_enterprise_preflight_container_rootless: false
ai_enterprise_preflight_sudo_group: wheel
ai_enterprise_product_repos: []
ai_enterprise_product_prereq_packages: []
ai_enterprise_product_required_secrets: []
ai_enterprise_product_required_mounts: []
ai_enterprise_installer_config_path: /etc/ai_enterprise-installer.conf
ai_enterprise_product_ports: []
ai_enterprise_install_deps: false
ai_enterprise_apply_changes: false
ai_enterprise_validate_platform_certs: false
ai_enterprise_show_help: false
ai_enterprise_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
ai_enterprise_container_runtime: podman
ai_enterprise_container_registry: registry.redhat.io

