---
# ansible-lint: skip_list=var-naming
rhel_ai_preflight_admin_user: \"{{ healthcheck_common_admin_user | default('admin') }}\"
rhel_ai_preflight_container_rootless: false
rhel_ai_preflight_sudo_group: \"{{ healthcheck_common_sudo_group | default('wheel') }}\"
rhel_ai_product_repos: []
rhel_ai_product_prereq_packages: []
rhel_ai_product_required_secrets: []
rhel_ai_product_required_mounts: []
rhel_ai_installer_config_path: /etc/rhel_ai-installer.conf
rhel_ai_product_ports: []
rhel_ai_install_deps: false
rhel_ai_apply_changes: false
rhel_ai_validate_platform_certs: false
rhel_ai_show_help: false
rhel_ai_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
rhel_ai_container_runtime: podman
rhel_ai_container_registry: registry.redhat.io
