---
# ansible-lint: skip_list=var-naming
openshift_preflight_admin_user: \"{{ healthcheck_common_admin_user | default('admin') }}\"
openshift_preflight_container_rootless: true
openshift_preflight_sudo_group: \"{{ healthcheck_common_sudo_group | default('wheel') }}\"
openshift_product_repos:
  - name: openshift-base
    description: OpenShift repository
    baseurl: ""
openshift_product_prereq_packages:
  - python3
  - python3-venv
  - python3-pip
  - podman
openshift_product_required_secrets:
  - admin_password
  - repo_baseurl
  - installer_token
openshift_product_required_mounts:
  - /var
  - /opt
  - /var/lib/registry
openshift_installer_config_path: /etc/openshift-installer.conf
