---
# ansible-lint: skip_list=var-naming
certificate_system_preflight_admin_user: \"{{ healthcheck_common_admin_user | default('admin') }}\"
certificate_system_preflight_container_rootless: false
certificate_system_preflight_sudo_group: \"{{ healthcheck_common_sudo_group | default('wheel') }}\"
certificate_system_product_repos: []
certificate_system_product_prereq_packages: []
certificate_system_product_required_secrets: []
certificate_system_product_required_mounts: []
certificate_system_installer_config_path: /etc/certificate_system-installer.conf
certificate_system_product_ports: []
certificate_system_install_deps: false
certificate_system_apply_changes: false
certificate_system_validate_platform_certs: false
certificate_system_show_help: false
certificate_system_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
certificate_system_container_runtime: podman
certificate_system_container_registry: registry.redhat.io
