---
# ansible-lint: skip_list=var-naming
satellite_preflight_admin_user: \"{{ healthcheck_common_admin_user | default('admin') }}\"
satellite_preflight_container_rootless: false
satellite_preflight_sudo_group: \"{{ healthcheck_common_sudo_group | default('wheel') }}\"
satellite_product_repos:
  - name: satellite-base
    description: Satellite repository
    baseurl: ""

satellite_product_prereq_packages:
  - python3
  - python3-venv
  - python3-pip

satellite_product_required_secrets:
  - admin_password
  - repo_baseurl
  - installer_token

satellite_product_required_mounts:
  - /var
  - /opt

satellite_product_ports:
  - 80
  - 443
  - 5647
  - 8000
  - 8140

satellite_installer_config_path: /etc/satellite-installer.conf

satellite_install_deps: false
satellite_apply_changes: false
satellite_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'

satellite_container_runtime: podman
satellite_container_registry: registry.redhat.io
satellite_validate_platform_certs: false
satellite_show_help: false
