---
# ansible-lint: skip_list=var-naming
directory_server_preflight_admin_user: \"{{ healthcheck_common_admin_user | default('admin') }}\"
directory_server_preflight_container_rootless: false
directory_server_preflight_sudo_group: \"{{ healthcheck_common_sudo_group | default('wheel') }}\"
directory_server_product_repos: []
directory_server_product_prereq_packages: []
directory_server_product_required_secrets: []
directory_server_product_required_mounts: []
directory_server_installer_config_path: /etc/directory_server-installer.conf
directory_server_product_ports: []
directory_server_install_deps: false
directory_server_apply_changes: false
directory_server_validate_platform_certs: false
directory_server_show_help: false
directory_server_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
directory_server_container_runtime: podman
directory_server_container_registry: registry.redhat.io
