---
# ansible-lint: skip_list=var-naming
application_foundations_preflight_admin_user: admin
application_foundations_preflight_container_rootless: false
application_foundations_preflight_sudo_group: wheel
application_foundations_product_repos: []
application_foundations_product_prereq_packages: []
application_foundations_product_required_secrets: []
application_foundations_product_required_mounts: []
application_foundations_installer_config_path: /etc/application_foundations-installer.conf
application_foundations_product_ports: []
application_foundations_install_deps: false
application_foundations_apply_changes: false
application_foundations_validate_platform_certs: false
application_foundations_show_help: false
application_foundations_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
application_foundations_container_runtime: podman
application_foundations_container_registry: registry.redhat.io
