---
# ansible-lint: skip_list=var-naming
insights_preflight_admin_user: admin
insights_preflight_container_rootless: false
insights_preflight_sudo_group: wheel
insights_product_repos: []
insights_product_prereq_packages: []
insights_product_required_secrets: []
insights_product_required_mounts: []
insights_installer_config_path: /etc/insights-installer.conf
insights_product_ports: []
insights_install_deps: false
insights_apply_changes: false
insights_validate_platform_certs: false
insights_show_help: false
insights_supported_rhel_major_versions:
  - '8'
  - '9'
  - '10'
insights_container_runtime: podman
insights_container_registry: registry.redhat.io
