---
- name: Red Hat Discovery HealthCheck
  hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    discovery_healthcheck_output_dir: "./discovery_reports"

  roles:
    - role: discovery_healthcheck
